### PR TITLE
adding a first pass at a list of xpaths for eml_profile

### PR DESCRIPTION
**Pull request by mobb**
Hi Mark and Jon -
Here is a draft of a set of xpaths for an "EML profile". It is basically a csv file with three fields:
concept_name
xpath 
frequency of use in pasta

I generated this file from 2 things: 
a. a datasets that Gastil, John Porter and Mary Martin created for an ESIP poster on common patterns of usage. 
b. a list of leaf-nodes from a typical EMLassemblyLine datasets. 
So the The "frequency" column reflects number of times those leaf nodes appeared in the snapshot of LTER and EDI-scoped datasets in 2019. 

As far as being a "profile", it is still incomplete: 
1. there are no XML-attribute nodes yet (these were not in the 2019 snapshot)
2. there may be nodes here that we do not want to support. 
3. there are probably nodes not included here (in addition to XML-attributes) that we may want to support.

So we will need to discuss changes. The Gastil-Porter-Martin snapshot dataset is in a postreSQL DB, which I  exported and processed with a bash script. Those materials will need to be publicly available as well (but are not yet)

### CODE REVIEW

**Comment by mobb** [comment]
I think we should focus on 2.2.
This draft does not yet have any 2.2 xpaths in it yet, however.

**Comment by servilla** [comment]
OK, sounds good to focus on 2.2.0 - looks like the analysis would need to be rerun in coming months, but make some manual inferences based on what know is hot. Note that metapype, at present, doe not support 2.2.0 features. Regarding the format:

> - **concept_name**: Mark asked for a simple name for the concept the xpath refers to. Currently, this column is a truncated, string version of the xpath itself. I am not sure what is most useful as a concept_name. options might be: 
>   - general, e.g., "adminstrativeArea", where ever that node appears (1:many with xpath, a key to an array)  
>   - specific, 1:1 with xpath (as it is now), so a key to an individual xpath. 
>   - something else.
> - **xpath**: leaf nodes only. this draft is a subset of leaf nodes in a snapshot of all contributed datasets (LTER and EDI scopes) available in July 2019. So it reflects xpaths in use.
> - **frequency**: count of instances of this xpath in all docs in the snapshot

1. I envision that the **concept name** is more of the natural language version of the leafnode element name of the xpath. This is not critical at this point and can be added over time.
1. I wonder if the **xpath** leaf node is sufficient to have a good understanding of its use? I am concerned that some leaf nodes are reused in different locations of the schema and may be context sensitive? That is, they may have a subtle semantic difference between contexts?
1. I assume that **frequency** simply reinforces which leaf nodes are important (by lots of use) and which one are not so important.

**Comment by servilla** [comment]
So lastly, I think it would be best to use the following directory path:
```
./docs/eml_profile/eml_2.1.0/...
./docs/eml_profile/eml_2.1.1/...
./docs/eml_profile/eml_2.2.2/...
```

**Comment by mobb** [comment]
> 1. I envision that the concept name is more of the natural language version of the leafnode element name of the xpath. This is not critical at this point and can be added over time.

I agree, this would be more useful. But I didn't have a a simple list of concepts we wanted to support that I could map xpaths to. I thought about using just the leaf node-name alone, maybe with one of its ancestor nodes.

> 2. I wonder if the xpath leaf node is sufficient to have a good understanding of its use? I am concerned that some leaf nodes are reused in different locations of the schema and may be context sensitive? That is, they may have a subtle semantic difference between contexts?

My script is pretty stupid, so right now, yes, it assumes leaf-node-name is a unique concept. EML is pretty self-explanatory, so it might be enough. And in some cases, there probably are no semantic differences (e.g, between `creator/*/adimistrativeArea` and `contact/*/administrativeArea`). I was thinking ahead to attribute-leafs, where attribute names are more often reused --  e.g., `id` is everywhere, and then the context (or xpath ancestors) matters.
 
> 3. I assume that frequency simply reinforces which leaf nodes are important (by lots of use) and which one are not so important.

yes, this is more of a place holder - an idea of how popular it is. but IMO, the profile should not be based only on popularity, although it is a consideration.

**Comment by mobb** [comment]
> So lastly, I think it would be best to use the following directory path:
> 
> ```
> ./docs/eml_profile/eml_2.1.0/...
> ./docs/eml_profile/eml_2.1.1/...
> ./docs/eml_profile/eml_2.2.2/...
> ```
sounds fine! do you want me to add that to the fork?

**Comment by servilla** [comment]
Yes, please - then I will merge.

**Pull request merged**
